x = read.csv('./exportTemp.csv',row.names=1)
x = (x-colMeans(x))
X = as.matrix(x)
A = X %*% t(X)
E = eigen(A, symmetric=TRUE)
P = E$values * t(E$vectors)
write.csv(t(P),'./rotationRow.csv',row.names=F)
valprop = E$values/sum(E$values)
pcaRes = list(x=X,eig=E,a=A,P=P,val=valprop)
val = pcaRes$val
nval = length(val)
png("././test_principalImage_Rowwise.png",width=480,height=480,bg="cornsilk")
par(mfrow=c(2,2))
a1 = 1
a2 = 2
a3 = 3
plot(pcaRes$P[a1,],pcaRes$P[a2,],"n",xlab=paste("axis 1:",val[a1]*100,"%"),ylab=paste("axis 2:",val[a2]*100,"%"),asp=1)
text(pcaRes$P[a1,],pcaRes$P[a2,],rownames(pcaRes$x),cex=0.75)
abline(h=0,lty=2,col="gray")
abline(v=0,lty=2,col="gray")
plot(pcaRes$P[a2,],pcaRes$P[a3,],"n",xlab=paste("axis 2:",val[a2]*100,"%"),ylab=paste("axis 3:",val[a3]*100,"%"),asp=1)
text(pcaRes$P[a2,],pcaRes$P[a3,],rownames(pcaRes$x),cex=0.75)
abline(h=0,lty=2,col="gray")
abline(v=0,lty=2,col="gray")
plot(pcaRes$P[a1,],pcaRes$P[a3,],"n",xlab=paste("axis 1:",val[a1]*100,"%"),ylab=paste("axis 3:",val[a3]*100,"%"),asp=1)
text(pcaRes$P[a1,],pcaRes$P[a3,],rownames(pcaRes$x),cex=0.75)
abline(h=0,v=0,lty=2,col="gray")
barplot(val[a1:nval]*100,names.arg=a1:nval,main="Axis inertia (in %)",col="orangered")
dev.off()
