# Saved performance Tableau: 
from decimal import Decimal
from collections import OrderedDict
actions = OrderedDict([
('a1', {
'shortName': 'a1a',
'name': 'action a1',
'comment': 'Cost-Benefit',
'type': 'advantageous',
}),
('a2', {
'shortName': 'a2a',
'name': 'action a2',
'comment': 'Cost-Benefit',
'type': 'advantageous',
}),
('a3', {
'shortName': 'a3a',
'name': 'action a3',
'comment': 'Cost-Benefit',
'type': 'advantageous',
}),
('a4', {
'shortName': 'a4n',
'name': 'action a4',
'comment': 'Cost-Benefit',
'type': 'neutral',
}),
('a5', {
'shortName': 'a5n',
'name': 'action a5',
'comment': 'Cost-Benefit',
'type': 'neutral',
}),
])
objectives = OrderedDict([
('C', {
'name': 'Costs',
'criteria': ['c1', 'c2', 'c3', 'c4'],
'weight': Decimal('12'),
}),
('B', {
'name': 'Benefits',
'criteria': ['b1', 'b2', 'b3'],
'weight': Decimal('12'),
}),
])
criteria = OrderedDict([
('c1', {
'preferenceDirection': 'min',
'scaleType': 'cardinal',
'objective': 'C',
'shortName': 'c1',
'name': 'random cardinal cost criterion',
'scale': (0.0, 100.0),
'weight': Decimal('3'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('1.5'), Decimal('0'))), ('pref', (Decimal('1.5'), Decimal('0'))), ('veto', (Decimal('58.47'), Decimal('0')))]),
}),
('b1', {
'preferenceDirection': 'max',
'scaleType': 'cardinal',
'objective': 'B',
'shortName': 'b1',
'name': 'random cardinal benefit criterion',
'scale': (0.0, 100.0),
'weight': Decimal('4'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('6.9'), Decimal('0'))), ('pref', (Decimal('6.9'), Decimal('0'))), ('veto', (Decimal('53.69'), Decimal('0')))]),
}),
('c2', {
'preferenceDirection': 'min',
'scaleType': 'cardinal',
'objective': 'C',
'shortName': 'c2',
'name': 'random cardinal cost criterion',
'scale': (0.0, 100.0),
'weight': Decimal('3'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('2.47'), Decimal('0'))), ('pref', (Decimal('2.47'), Decimal('0'))), ('veto', (Decimal('36.09'), Decimal('0')))]),
}),
('b2', {
'preferenceDirection': 'max',
'scaleType': 'cardinal',
'objective': 'B',
'shortName': 'b2',
'name': 'random cardinal benefit criterion',
'scale': (0.0, 100.0),
'weight': Decimal('4'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('4.95'), Decimal('0'))), ('pref', (Decimal('4.95'), Decimal('0'))), ('veto', (Decimal('47.06'), Decimal('0')))]),
}),
('c3', {
'preferenceDirection': 'min',
'scaleType': 'ordinal',
'objective': 'C',
'shortName': 'c3',
'name': 'random ordinal cost criterion',
'scale': (0, 10),
'weight': Decimal('3'),
'randomMode': ['triangular', 5.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict(),
}),
('c4', {
'preferenceDirection': 'min',
'scaleType': 'cardinal',
'objective': 'C',
'shortName': 'c4',
'name': 'random cardinal cost criterion',
'scale': (0.0, 100.0),
'weight': Decimal('3'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('6.01'), Decimal('0'))), ('pref', (Decimal('6.01'), Decimal('0'))), ('veto', (Decimal('48.58'), Decimal('0')))]),
}),
('b3', {
'preferenceDirection': 'max',
'scaleType': 'ordinal',
'objective': 'B',
'shortName': 'b3',
'name': 'random ordinal benefit criterion',
'scale': (0, 10),
'weight': Decimal('4'),
'randomMode': ['triangular', 5.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict(),
}),
])
evaluation = {
'c1': {
'a1':Decimal("-73.93"),
'a2':Decimal("-86.39"),
'a3':Decimal("-75.43"),
'a4':Decimal("-39.54"),
'a5':Decimal("-27.92"),
},
'b1': {
'a1':Decimal("54.90"),
'a2':Decimal("73.62"),
'a3':Decimal("61.80"),
'a4':Decimal("43.76"),
'a5':Decimal("19.93"),
},
'c2': {
'a1':Decimal("-37.24"),
'a2':Decimal("-70.86"),
'a3':Decimal("-73.33"),
'a4':Decimal("-44.18"),
'a5':Decimal("-64.33"),
},
'b2': {
'a1':Decimal("66.09"),
'a2':Decimal("73.23"),
'a3':Decimal("48.62"),
'a4':Decimal("31.12"),
'a5':Decimal("26.17"),
},
'c3': {
'a1':Decimal("-6.00"),
'a2':Decimal("-8.00"),
'a3':Decimal("-3.00"),
'a4':Decimal("-6.00"),
'a5':Decimal("-4.00"),
},
'c4': {
'a1':Decimal("-74.84"),
'a2':Decimal("-82.56"),
'a3':Decimal("-91.76"),
'a4':Decimal("-43.18"),
'a5':Decimal("-49.19"),
},
'b3': {
'a1':Decimal("2.00"),
'a2':Decimal("2.00"),
'a3':Decimal("1.00"),
'a4':Decimal("6.00"),
'a5':Decimal("4.00"),
},
}
