# Saved performance Tableau: 
from decimal import Decimal
from collections import OrderedDict
actions = OrderedDict([
('a1', {
'shortName': 'a1a',
'name': 'action a1',
'comment': 'Cost-Benefit',
'type': 'advantageous',
}),
('a2', {
'shortName': 'a2n',
'name': 'action a2',
'comment': 'Cost-Benefit',
'type': 'neutral',
}),
('a3', {
'shortName': 'a3n',
'name': 'action a3',
'comment': 'Cost-Benefit',
'type': 'neutral',
}),
('a4', {
'shortName': 'a4n',
'name': 'action a4',
'comment': 'Cost-Benefit',
'type': 'neutral',
}),
('a5', {
'shortName': 'a5c',
'name': 'action a5',
'comment': 'Cost-Benefit',
'type': 'cheap',
}),
])
objectives = OrderedDict([
('C', {
'name': 'Costs',
'criteria': ['c1', 'c2'],
'weight': Decimal('10'),
}),
('B', {
'name': 'Benefits',
'criteria': ['b1', 'b2', 'b3', 'b4', 'b5'],
'weight': Decimal('10'),
}),
])
criteria = OrderedDict([
('c1', {
'preferenceDirection': 'min',
'scaleType': 'cardinal',
'objective': 'C',
'shortName': 'c1',
'name': 'random cardinal cost criterion',
'scale': (0.0, 100.0),
'weight': Decimal('5'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('4.7'), Decimal('0'))), ('pref', (Decimal('4.7'), Decimal('0'))), ('veto', (Decimal('45.48'), Decimal('0')))]),
}),
('b1', {
'preferenceDirection': 'max',
'scaleType': 'cardinal',
'objective': 'B',
'shortName': 'b1',
'name': 'random cardinal benefit criterion',
'scale': (0.0, 100.0),
'weight': Decimal('2'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('0.46'), Decimal('0'))), ('pref', (Decimal('0.46'), Decimal('0'))), ('veto', (Decimal('39.42'), Decimal('0')))]),
}),
('b2', {
'preferenceDirection': 'max',
'scaleType': 'cardinal',
'objective': 'B',
'shortName': 'b2',
'name': 'random cardinal benefit criterion',
'scale': (0.0, 100.0),
'weight': Decimal('2'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('1.05'), Decimal('0'))), ('pref', (Decimal('1.05'), Decimal('0'))), ('veto', (Decimal('23.11'), Decimal('0')))]),
}),
('c2', {
'preferenceDirection': 'min',
'scaleType': 'ordinal',
'objective': 'C',
'shortName': 'c2',
'name': 'random ordinal cost criterion',
'scale': (0, 10),
'weight': Decimal('5'),
'randomMode': ['triangular', 5.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict(),
}),
('b3', {
'preferenceDirection': 'max',
'scaleType': 'cardinal',
'objective': 'B',
'shortName': 'b3',
'name': 'random cardinal benefit criterion',
'scale': (0.0, 100.0),
'weight': Decimal('2'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('4.88'), Decimal('0'))), ('pref', (Decimal('4.88'), Decimal('0'))), ('veto', (Decimal('47.29'), Decimal('0')))]),
}),
('b4', {
'preferenceDirection': 'max',
'scaleType': 'cardinal',
'objective': 'B',
'shortName': 'b4',
'name': 'random cardinal benefit criterion',
'scale': (0.0, 100.0),
'weight': Decimal('2'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('3.46'), Decimal('0'))), ('pref', (Decimal('3.46'), Decimal('0'))), ('veto', (Decimal('54.43'), Decimal('0')))]),
}),
('b5', {
'preferenceDirection': 'max',
'scaleType': 'ordinal',
'objective': 'B',
'shortName': 'b5',
'name': 'random ordinal benefit criterion',
'scale': (0, 10),
'weight': Decimal('2'),
'randomMode': ['triangular', 5.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict(),
}),
])
NA = Decimal('-999')
evaluation = {
'c1': {
'a1':Decimal("-60.30"),
'a2':Decimal("-72.49"),
'a3':Decimal("-35.04"),
'a4':Decimal("-27.01"),
'a5':Decimal("-39.74"),
},
'b1': {
'a1':Decimal("50.47"),
'a2':Decimal("66.82"),
'a3':Decimal("67.30"),
'a4':Decimal("27.88"),
'a5':Decimal("28.34"),
},
'b2': {
'a1':Decimal("30.47"),
'a2':Decimal("50.34"),
'a3':Decimal("41.91"),
'a4':Decimal("49.29"),
'a5':Decimal("53.58"),
},
'c2': {
'a1':Decimal("-7.00"),
'a2':Decimal("-4.00"),
'a3':Decimal("-8.00"),
'a4':Decimal("-4.00"),
'a5':Decimal("-3.00"),
},
'b3': {
'a1':Decimal("75.28"),
'a2':Decimal("50.88"),
'a3':Decimal("55.76"),
'a4':Decimal("33.05"),
'a5':Decimal("80.34"),
},
'b4': {
'a1':Decimal("40.42"),
'a2':Decimal("61.67"),
'a3':Decimal("36.96"),
'a4':Decimal("19.98"),
'a5':Decimal("74.41"),
},
'b5': {
'a1':Decimal("5.00"),
'a2':Decimal("4.00"),
'a3':Decimal("9.00"),
'a4':Decimal("5.00"),
'a5':Decimal("1.00"),
},
}
