# Saved performance Tableau: 
from decimal import Decimal
from collections import OrderedDict
actions = OrderedDict([
('a1', {
'shortName': 'a1n',
'name': 'action a1',
'comment': 'Cost-Benefit',
'type': 'neutral',
}),
('a2', {
'shortName': 'a2c',
'name': 'action a2',
'comment': 'Cost-Benefit',
'type': 'cheap',
}),
('a3', {
'shortName': 'a3a',
'name': 'action a3',
'comment': 'Cost-Benefit',
'type': 'advantageous',
}),
('a4', {
'shortName': 'a4c',
'name': 'action a4',
'comment': 'Cost-Benefit',
'type': 'cheap',
}),
('a5', {
'shortName': 'a5a',
'name': 'action a5',
'comment': 'Cost-Benefit',
'type': 'advantageous',
}),
])
objectives = OrderedDict([
('C', {
'name': 'Costs',
'criteria': ['c1', 'c2', 'c3'],
'weight': Decimal('12'),
}),
('B', {
'name': 'Benefits',
'criteria': ['b1', 'b2', 'b3', 'b4'],
'weight': Decimal('12'),
}),
])
criteria = OrderedDict([
('c1', {
'preferenceDirection': 'min',
'scaleType': 'cardinal',
'objective': 'C',
'shortName': 'c1',
'name': 'random cardinal cost criterion',
'scale': (0.0, 100.0),
'weight': Decimal('4'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('1.24'), Decimal('0'))), ('pref', (Decimal('1.24'), Decimal('0'))), ('veto', (Decimal('78.58'), Decimal('0')))]),
}),
('b1', {
'preferenceDirection': 'max',
'scaleType': 'ordinal',
'objective': 'B',
'shortName': 'b1',
'name': 'random ordinal benefit criterion',
'scale': (0, 10),
'weight': Decimal('3'),
'randomMode': ['triangular', 5.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict(),
}),
('c2', {
'preferenceDirection': 'min',
'scaleType': 'ordinal',
'objective': 'C',
'shortName': 'c2',
'name': 'random ordinal cost criterion',
'scale': (0, 10),
'weight': Decimal('4'),
'randomMode': ['triangular', 5.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict(),
}),
('b2', {
'preferenceDirection': 'max',
'scaleType': 'ordinal',
'objective': 'B',
'shortName': 'b2',
'name': 'random ordinal benefit criterion',
'scale': (0, 10),
'weight': Decimal('3'),
'randomMode': ['triangular', 5.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict(),
}),
('b3', {
'preferenceDirection': 'max',
'scaleType': 'ordinal',
'objective': 'B',
'shortName': 'b3',
'name': 'random ordinal benefit criterion',
'scale': (0, 10),
'weight': Decimal('3'),
'randomMode': ['triangular', 5.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict(),
}),
('c3', {
'preferenceDirection': 'min',
'scaleType': 'cardinal',
'objective': 'C',
'shortName': 'c3',
'name': 'random cardinal cost criterion',
'scale': (0.0, 100.0),
'weight': Decimal('4'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('7.71'), Decimal('0'))), ('pref', (Decimal('7.71'), Decimal('0'))), ('veto', (Decimal('49.94'), Decimal('0')))]),
}),
('b4', {
'preferenceDirection': 'max',
'scaleType': 'cardinal',
'objective': 'B',
'shortName': 'b4',
'name': 'random cardinal benefit criterion',
'scale': (0.0, 100.0),
'weight': Decimal('3'),
'randomMode': ['triangular', 50.0, 0.5],
'comment': 'Evaluation generator: triangular law with variable mode (m) and probability repartition (p = 0.5). Cheap actions: m = 30%; neutral actions: m = 50%; advantageous actions: m = 70%.',
'thresholds': OrderedDict([('ind', (Decimal('4.73'), Decimal('0'))), ('pref', (Decimal('4.73'), Decimal('0'))), ('veto', (Decimal('53.14'), Decimal('0')))]),
}),
])
NA = Decimal('-999')
evaluation = {
'c1': {
'a1':Decimal("-50.19"),
'a2':Decimal("-15.15"),
'a3':Decimal("-93.73"),
'a4':Decimal("-43.09"),
'a5':Decimal("-48.95"),
},
'b1': {
'a1':Decimal("5.00"),
'a2':Decimal("5.00"),
'a3':Decimal("7.00"),
'a4':Decimal("3.00"),
'a5':Decimal("4.00"),
},
'c2': {
'a1':Decimal("-5.00"),
'a2':Decimal("-6.00"),
'a3':Decimal("-3.00"),
'a4':Decimal("-4.00"),
'a5':Decimal("-9.00"),
},
'b2': {
'a1':Decimal("4.00"),
'a2':Decimal("2.00"),
'a3':Decimal("9.00"),
'a4':Decimal("1.00"),
'a5':Decimal("8.00"),
},
'b3': {
'a1':Decimal("7.00"),
'a2':Decimal("1.00"),
'a3':Decimal("9.00"),
'a4':Decimal("4.00"),
'a5':Decimal("9.00"),
},
'c3': {
'a1':Decimal("-38.03"),
'a2':Decimal("-48.90"),
'a3':Decimal("-87.97"),
'a4':Decimal("-56.61"),
'a5':Decimal("-71.39"),
},
'b4': {
'a1':Decimal("17.47"),
'a2':Decimal("12.74"),
'a3':Decimal("49.20"),
'a4':Decimal("40.33"),
'a5':Decimal("65.88"),
},
}
