.. _UnOpposed-Outranking-Tutorial-label:

Outrankings unopposed by multiple decision objectives
-----------------------------------------------------

.. contents:: 
	:depth: 1
	:local:

Besides the previously discussed *confident* and *stable* outranking situations, we may, when facing a multiple objectives decision problem observe a further type of interesting multiple criteria outranking situations. Namely, outranking situations that are validated for one or more decision objectives and not invalidated by any other decision objective.

Unopposed outranking situations
...............................

Given two potential decision alternatives *x* and *y*.

We say that '*x* **unopposed** outranks *y*' when *x* positively outranks *y* on one or more decision objectives *and* *x* does not negatively outrank *y* on any other decision objective.

Symmetrically, ee say that '*x* **unopposed** does not outrank *y*' when *x* negatively outranks *y*  on one or more decision objectives *and* *x* does not positively outrank *y* on any other decision objective.

Let us consider an example.

.. code-block:: pycon
   :linenos:
   :caption: A random multiple objectives decision problem
   :name: multobjExample

   >>> from outrankingDigraphs import\
            Random3ObjectivesPerformanceTableau
   >>> nba = 7
   >>> nbc = 9
   >>> t = Random3ObjectivesPerformanceTableau(\
            numberOfActions=nba,\
            numberOfCriteria=nbc,\
            weightDistribution='equisignificant',\
            seed= 102,\
            )
   >>> t.showObjectives()
    *------ show objectives -------"
    Eco: Economical aspect
     ec1 criterion of objective Eco 1
     ec4 criterion of objective Eco 1
     ec8 criterion of objective Eco 1
    Total weight: 3.00 (3 criteria)
    Soc: Societal aspect
     so2 criterion of objective Soc 1
     so7 criterion of objective Soc 1
    Total weight: 2.00 (2 criteria)
    Env: Environmental aspect
     en3 criterion of objective Env 1
     en5 criterion of objective Env 1
     en6 criterion of objective Env 1
     en9 criterion of objective Env 1
    Total weight: 4.00 (4 criteria)

We discover in :numref:`multobjExample` a three objectives social decision problem involving seven potential public policiesevaluated on nine equisignificant performance criteria. The most important objective *Env*, evaluated on four performance criteria, concerns the environmental aspect. The second most important objective *Eco*, with three performance criteria concerns the economical aspect. And, the third objective *Soc*, the lesse important one with two performance criteria, concerns the societal aspect.

Computing the corresponding standard and *unopposed* outranking situations may be done with the :py:code:`BipolarOutrankingDigraph` and the :py:class:`outrankingDigraphs.UnOpposedBipolarOutrankingDigraph` classes.

.. code-block:: pycon
   :linenos:
   :caption: unopposed outranking situations
   :name: unopposedSituations

   >>> from outrankingDigraphs import\
	    BipolarOutrankingDigraph,\
	    UnOpposedBipolarOutrankingDigraph
   >>> g = BipolarOutrankingDigraph(t)
   >>> g.showRelationTable(ReflexiveTerms=False)
    * ---- Relation Table -----
     r   |  'p1'   'p2'   'p3'   'p4'   'p5'   'p6'   'p7'   
    'p1' |     -   -0.22  +0.11  -0.67  +0.44  +0.11  +0.11  
    'p2' |   +0.44    -   +0.78  +0.00  +0.44  +0.44  +0.44  
    'p3' |   +0.22  -0.22    -   -0.11  +0.56  +1.00  +0.33  
    'p4' |   +0.78  +1.00  +0.67    -   +1.00  +1.00  +0.78  
    'p5' |   -0.11  -0.33  -0.22  -0.89    -   +0.11  +0.00  
    'p6' |   +0.11  -0.22  +0.00  -1.00  +0.22    -   +0.00  
    'p7' |   +0.11  -0.33  +0.11  -0.22  +0.78  +0.33    -   
    Valuation domain: [-1.000; 1.000]
   >>> uog = UnOpposedBipolarOutrankingDigraph(t)
   >>> uog.showRelationTable(ReflexiveTerms=False)
    * ---- Relation Table -----
     r   |  'p1'   'p2'   'p3'   'p4'   'p5'   'p6'   'p7'   
    'p1' |     -   +0.00  +0.00  -0.67  +0.44  +0.11  +0.00  
    'p2' |   +0.00    -   +0.78  +0.00  +0.00  +0.00  +0.00  
    'p3' |   +0.00  -0.22    -   +0.00  +0.56  +0.00  +0.00  
    'p4' |   +0.78  +0.00  +0.67    -   +1.00  +1.00  +0.78  
    'p5' |   -0.11  +0.00  +0.00  -0.89    -   +0.11  +0.00  
    'p6' |   +0.00  +0.00  +0.00  -0.56  +0.22    -   +0.00  
    'p7' |   +0.00  +0.00  +0.00  +0.00  +0.78  +0.33    -   
    Valuation domain: [-1.000; 1.000]
   >>> print(uog.computeSize()/g.computeSize())
    0.50

About 50% of the standard outranking situations appear to qualify as *unopposed* ones. This is, for instance the case for the pairwise comparison of policies *p2* and *p3*.

>>> g.showPairwiseComparison('p2','p3')
*------------  pairwise comparison ----*
Comparing actions : (p2, p3)
crit. wght.  g(x)  g(y)    diff   | ind   pref    r()
ec1   1.00  89.77  80.19  +9.58   | 5.00  10.00   +1.00  
ec4   1.00  86.00  68.70  +17.30  | 5.00  10.00   +1.00 
ec8   1.00  89.43  91.94  -2.51   | 5.00  10.00   +1.00 	
en3   1.00  20.79  46.78  -25.99  | 5.00  10.00   -1.00  
en5   1.00  23.83  27.25  -3.42   | 5.00  10.00   +1.00  
en6   1.00  18.66  1.65  +17.01   | 5.00  10.00   +1.00 
en9   1.00  26.65  14.85  +11.80  | 5.00  10.00   +1.00
so2   1.00  89.12  58.85  +30.27  | 5.00  10.00   +1.00
so7   1.00  84.73  15.49  +69.24  | 5.00  10.00   +1.00 
 Valuation in range: -9.00 to +9.00;
 Global concordance: +7.00 (0.78)

Policy *p2* outranks indeed plociy *p3* on all the three decision objectives. When comparing, however, policies *p3* and *p5*, we observe only two positive objectives, as an indeterminate situation appears with respect to the societal aspect.

>>> g.showPairwiseComparison('p3','p5')
*------------  pairwise comparison ----*
Comparing actions : (p3, p5)
crit. wght.  g(x)  g(y)    diff   | ind   pref    r() 
ec1   1.00  80.19  46.75  +33.44  | 5.00  10.00   +1.00 
ec4   1.00  68.70  8.96  +59.74   | 5.00  10.00   +1.00  
ec8   1.00  91.94  35.91  +56.03  | 5.00  10.00   +1.00 
en3   1.00  46.78  31.05  +15.73  | 5.00  10.00   +1.00  
en5   1.00  27.25  29.52  -2.27   | 5.00  10.00   +1.00
en6   1.00  1.65  31.22  -29.57   | 5.00  10.00   -1.00  
en9   1.00  14.85  9.83  +5.02 	  | 5.00  10.00   +1.00  
so2   1.00  58.85  12.36  +46.49  | 5.00  10.00   +1.00  
so7   1.00  15.49  44.92  -29.43  | 5.00  10.00   -1.00  
 Valuation in range: -9.00 to +9.00;
 Global concordance: +5.00 (0.22)
 
Let us mention that the stability level 3 qualified outranking situations, seen in the previous section, represent in fact a special case of *unopposedness*. Indeed, the criteria weights equivalence classes where matching exactly the objectives colaitions such that all level three qualifies situations also qualify for unopposed outranking situations.

Computing the unopposed bipolar-valued unopposed outranking digraph is operated with the help of the **average fusion** :py:meth:`digraphsTools.o_average` operator. 

Objectives outrankings fusion
.............................

to be written


Bibliography
------------
	  
.. [BIS-2015p] Bisdorff R. (2015). "The EURO 2004 Best Poster Award: Choosing the Best Poster in a Scientific Conference". Chapter 5 in R. Bisdorff, L. Dias, P. Meyer, V. Mousseau, and M. Pirlot (Eds.), *Evaluation and Decision Models with Multiple Criteria: Case Studies*. Springer-Verlag Berlin Heidelberg, International Handbooks on Information Systems, DOI 10.1007/978-3-662-46816-6_1, pp. 117-166 (downloadable `PDF file 754.7 kB <http://hdl.handle.net/10993/23714>`_).
	       
.. [BIS-2014p] Bisdorff R., Meyer P. and Veneziano Th. (2014). "Elicitation of criteria weights maximising the stability of pairwise outranking statements". *Journal of Multi-Criteria Decision Analysis* (Wiley) 21: 113-124 (downloadable preprint `PDF file 431.4 Kb <http://hdl.handle.net/10993/23701>`_).
   
.. [BIS-2013p] Bisdorff R. (2013) "On Polarizing Outranking Relations with Large Performance Differences" *Journal of Multi-Criteria Decision Analysis* (Wiley) **20**:3-12 (downloadable preprint `PDF file 403.5 Kb <http://hdl.handle.net/10993/245>`_).

.. [BIS-2012p] Bisdorff R. (2012). "On measuring and testing the ordinal correlation between bipolar outranking relations". In Proceedings of DA2PL’2012 *From Multiple Criteria Decision Aid to Preference Learning*, University of Mons 91-100. (downloadable preliminary version `PDF file 408.5 kB <http://hdl.handle.net/10993/23909>`_ ).

.. [BIS-2006_1p] Bisdorff R., Pirlot M. and Roubens M. (2006). "Choices and kernels from bipolar valued digraphs". *European Journal of Operational Research*, 175 (2006) 155-170. (Online) Electronic version: DOI:10.1016/j.ejor.2005.05.004 (downloadable preliminary version `PDF file 257.3Kb <http://hdl.handle.net/10993/23720>`_).

.. [BIS-2006_2p] Bisdorff R. (2006). "On enumerating the kernels in a bipolar-valued digraph". *Annales du Lamsade* 6, Octobre 2006, pp. 1 - 38. Université Paris-Dauphine. ISSN 1762-455X (downloadable version `PDF file 532.2 Kb <http://hdl.handle.net/10993/38741>`_).

.. [BIS-2004_1p] Bisdorff R. (2004). "Concordant Outranking with multiple criteria of ordinal significance". 4OR, *Quarterly Journal of the Belgian, French and Italian Operations Research Societies*, Springer-Verlag, Issue: Volume 2, Number 4, December 2004, Pages: 293 - 308. [ISSN: 1619-4500 (Paper) 1614-2411 (Online)] Electronic version: DOI: 10.1007/s10288-004-0053-7 (downloadable preliminary version `PDF file 137.1Kb <http://hdl.handle.net/10993/23721>`_)

.. [BIS-2004_2p] Bisdorff R. (2004). Preference aggregation with multiple criteria of ordinal significance. In: D. Bouyssou, M. Janowitz, F. Roberts, and A. Tsouki´s (eds.), Annales du LAMSADE, 3, Octobre 2004, Université Paris-Dauphine, pp. 25-44 [ISSN 1762-455X] (downloadable `PDF file 167.6Kb <http://hdl.handle.net/10993/42420>`_).
   
.. [SCH-1985p] Schmidt G. and Ströhlein Th. (1985), "On kernels of graphs and solutions of games: a synopsis based on relations and fixpoints". SIAM, J. *Algebraic Discrete Methods*, 6, 1985, 54–65.

.. [BER-1958p] Berge C. (2001), *The theory of graphs*. Dover Publications Inc. 2001. First published in English by Methuen & Co Ltd., London 1962. Translated from a French edition by Dunod, Paris 1958.

.. [KEN-1938p] Kendall M.G. (1938), "A New Measure of Rank Correlation". *Biometrica* 30:81–93

.. only:: html
	  
    Documents
    .........
     
    * `Introduction <index.html>`_
    * `Reference manual <techDoc.html>`_
    * `Tutorial <tutorial.html>`_

.. only:: html

    Footnotes
    .........

.. [1] *Graffiti*, Edition Revue Luxembourg, September 2007, p. 30. You may find the data file *graffiti07.py* (perfTabs.PerformanceTableau Format) in the *examples* directory of the Digraph3 ressources.       

.. [2] The 3D PCA plot method requires a running *R statistics software*  (https://www.r-project.org/) installation and the Calmat matrix calculator (see the calmat directory in the Digraph3 ressources)

.. [3] A *kernel* in a digraph *g* is a *clique* in the dual digraph *-g*.

.. [4] The Gnu Regression, Econometrics and Time-series Library http://gretl.sourceforge.net/ .

.. raw:: latex

   \endgroup

