# Saved performance Tableau: 
from decimal import Decimal
from collections import OrderedDict
description = {
'title': 'THE World University Rankings 2016-2017 by subject: computer science', 
'version': '26.10.2016',
'comment': 'https://www.timeshighereducation.com/world-university-rankings/2017/subject-ranking/computer-science'
}
actions = OrderedDict([
('albt', {
'name': 'University of Alberta',
'comment': 'CA',
}),
('anu', {
'name': 'Australian National University',
'comment': 'AU',
}),
('ariz', {
'name': 'Arizona State University',
'comment': 'US',
}),
('bju', {
'name': 'Beijing University',
'comment': 'CN',
}),
('bro', {
'name': 'Brown University',
'comment': 'US',
}),
('calt', {
'name': 'Califormia Institute of Technology',
'comment': 'US',
}),
('cbu', {
'name': 'Columbia University',
'comment': 'US',
}),
('chku', {
'name': 'Chinese University of Hong Kong',
'comment': 'HK',
}),
('cihk', {
'name': 'City University of Hong Kong',
'comment': 'HK',
}),
('cir', {
'name': 'University of California at Irwine',
'comment': 'US',
}),
('cmel', {
'name': 'Carnegie Mellon University',
'comment': 'US',
}),
('cou', {
'name': 'Cornell University',
'comment': 'US',
}),
('csb', {
'name': 'University of California at Santa Barbara',
'comment': 'US',
}),
('csd', {
'name': 'University Of California at San Diego',
'comment': 'US',
}),
('dut', {
'name': 'Delft University of Technology',
'comment': 'NL',
}),
('eind', {
'name': 'Eindhoven University of Technology',
'comment': 'NL',
}),
('ens', {
'name': 'Superior Normal School at Paris',
'comment': 'FR',
}),
('epfl', {
'name': 'Swiss Federal Institute of Technology Lausanne',
'comment': 'CH',
}),
('epfr', {
'name': 'Polytechnic school of Paris',
'comment': 'FR',
}),
('ethz', {
'name': 'Swiss Federal Institute of Technology Zürich',
'comment': 'CH',
}),
('frei', {
'name': 'University of Freiburg',
'comment': 'DE',
}),
('git', {
'name': 'Georgia Institute of Technology',
'comment': 'US',
}),
('glas', {
'name': 'University of Glasgow',
'comment': 'UK',
}),
('hels', {
'name': 'University of Helsinki',
'comment': 'FI',
}),
('hkpu', {
'name': 'Hong Kong Polytechnic University',
'comment': 'CN',
}),
('hkst', {
'name': 'Hong Kong University of Science and Technology',
'comment': 'HK',
}),
('hku', {
'name': 'Hong Kong University',
'comment': 'HK',
}),
('humb', {
'name': 'Berlin Humboldt University',
'comment': 'DE',
}),
('icl', {
'name': 'Imperial College London',
'comment': 'UK',
}),
('indis', {
'name': 'Indian Institute of Science',
'comment': 'IN',
}),
('itmo', {
'name': 'ITMO University',
'comment': 'RU',
}),
('kcl', {
'name': "King's College London",
'comment': 'UK',
}),
('kist', {
'name': 'Korea Advances Institute of Science and Tecnology',
'comment': 'KR',
}),
('kit', {
'name': 'Karlsruhe Institute of Technology',
'comment': 'DE',
}),
('kth', {
'name': 'KTH Royal Institute of Technology',
'comment': 'SE',
}),
('kuj', {
'name': 'Kyoto University',
'comment': 'JP',
}),
('kul', {
'name': 'Katholieke Universiteit Leuven',
'comment': 'BE',
}),
('lms', {
'name': 'Lomonosov Moscow State University',
'comment': 'RU',
}),
('man', {
'name': 'University of Manchester',
'comment': 'UK',
}),
('mcp', {
'name': 'University of Maryland College Park',
'comment': 'US',
}),
('mel', {
'name': 'University of Melbourne',
'comment': 'AU',
}),
('mil', {
'name': 'Polytechnic University of Milan',
'comment': 'IT',
}),
('mit', {
'name': 'Massachusetts Institute of Technology',
'comment': 'US',
}),
('naji', {
'name': 'Nanjing University',
'comment': 'CN',
}),
('ntu', {
'name': 'Nanyang Technological University of Singapore',
'comment': 'SG',
}),
('ntw', {
'name': 'National Taiwan University',
'comment': 'TW',
}),
('nyu', {
'name': 'New York University',
'comment': 'US',
}),
('oxf', {
'name': 'University of Oxford',
'comment': 'UK',
}),
('pud', {
'name': 'Purdue University',
'comment': 'US',
}),
('qut', {
'name': 'Queensland University of Technology',
'comment': 'AU',
}),
('rcu', {
'name': 'Rice University',
'comment': 'US',
}),
('rwth', {
'name': 'RWTH Aachen University',
'comment': 'DE',
}),
('shJi', {
'name': 'Shanghai Jiao Tong University',
'comment': 'CN',
}),
('sing', {
'name': 'National University of Singapore',
'comment': 'SG',
}),
('sou', {
'name': 'University of Southhampton',
'comment': 'UK',
}),
('stut', {
'name': 'University of Stutgart',
'comment': 'DE',
}),
('tech', {
'name': 'Technion - Israel Institute of Technology',
'comment': 'IL',
}),
('tlavu', {
'name': 'Tel Aviv University',
'comment': 'IR',
}),
('tsu', {
'name': 'Tsinghua University',
'comment': 'CN',
}),
('tub', {
'name': 'Technical University of Berlin',
'comment': 'DE',
}),
('tud', {
'name': 'Technical University of Darmstadt',
'comment': 'DE',
}),
('tum', {
'name': 'Technical University of München',
'comment': 'DE',
}),
('ucl', {
'name': 'University College London',
'comment': 'UK',
}),
('ued', {
'name': 'University of Edinburgh',
'comment': 'UK',
}),
('uiu', {
'name': 'University of Illinois at Urbana-Champagne',
'comment': 'US',
}),
('unlu', {
'name': 'University of Luxembourg',
'comment': 'LU',
}),
('unsw', {
'name': 'University of New South Wales',
'comment': 'AU',
}),
('unt', {
'name': 'University of Toronto',
'comment': 'CA',
}),
('uta', {
'name': 'University of Texas at Austin',
'comment': 'US',
}),
('utj', {
'name': 'University of Tokyo',
'comment': 'JP',
}),
('utw', {
'name': 'University of Twente',
'comment': 'NL',
}),
('uwa', {
'name': 'University of Waterloo',
'comment': 'CA',
}),
('wash', {
'name': 'University of Washington',
'comment': 'US',
}),
('wtu', {
'name': 'Vienna University of Technology',
'comment': 'AUS',
}),
('zhej', {
'name': 'Zhejiang University',
'comment': 'CN',
}),
])
objectives = OrderedDict([
    ('Teaching',{'name':'Best learning environment',
             'comment':'Reputation survey; Staff-to-student ration; Doctorate-to-student ratio, Doctorate-to-academic-staff ratio, Institutional income.',
             'criteria':['gtch'],
             'weight':Decimal('30.0')}),
   ('Research',{'name':'Highest volume and repustation',
            'comment':'Reputation survey; Research income; Research productivity',
            'criteria':['gres'],
            'weight':Decimal('30.0')}),
   ('Citations',{'name':'Highest research influence',
            'comment':'Impact',
            'criteria':['gcit'],
            'weight':Decimal('27.5')}),
   ('International outlook',{'name':'Most international staff, students and research',
            'comment':'Proportion of international students; - of international staff; international collaborations',
            'criteria':['gint'],
            'weight':Decimal('7.5'),
            }),
   ('Industry income',{'name':'Best knowledge transfer',
            'comment':'Volume',
            'criteria':['gind'],
            'weight':Decimal('5.0'),
            }),
])
criteria = OrderedDict([
('gtch', {
'name': 'Teaching',
'comment': 'The learning environment',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('100.00')),
'weight': Decimal('30.00'),
'thresholds': {'ind': (Decimal('2.50'), Decimal('0.0')), 'pref': (Decimal('5.00'), Decimal('0.0')), 'veto': (Decimal('60.00'), Decimal('0.0'))},
}),
('gres', {
'name': 'Research',
'comment': 'Volume, income and reputation',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('100.00')),
'weight': Decimal('30.00'),
'thresholds': {'ind': (Decimal('2.50'), Decimal('0.0')), 'pref': (Decimal('5.00'), Decimal('0.0')), 'veto': (Decimal('60.00'), Decimal('0.0'))},
}),
('gcit', {
'name': 'Citations',
'comment': 'Research influence',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('100.00')),
'weight': Decimal('27.50'),
'thresholds': {'ind': (Decimal('2.50'), Decimal('0.0')), 'pref': (Decimal('5.00'), Decimal('0.0')), 'veto': (Decimal('60.00'), Decimal('0.0'))},
}),
('gint', {
'name': 'International outlook',
'comment': 'In staff, students and research',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('100.00')),
'weight': Decimal('7.50'),
'thresholds': {'ind': (Decimal('2.50'), Decimal('0.0')), 'pref': (Decimal('5.00'), Decimal('0.0'))},
}),
('gind', {
'name': 'Industry income',
'comment': 'Knowledge transfer',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('100.00')),
'weight': Decimal('5.00'),
'thresholds': {'ind': (Decimal('2.50'), Decimal('0.0')), 'pref': (Decimal('5.00'), Decimal('0.0'))},
}),
])
evaluation = {
'gcit': {
'albt':Decimal("69.90"),
'anu':Decimal("92.20"),
'ariz':Decimal("84.30"),
'bju':Decimal("70.10"),
'bro':Decimal("96.80"),
'calt':Decimal("99.80"),
'cbu':Decimal("94.70"),
'chku':Decimal("94.70"),
'cihk':Decimal("80.10"),
'cir':Decimal("93.00"),
'cmel':Decimal("99.40"),
'cou':Decimal("99.70"),
'csb':Decimal("94.80"),
'csd':Decimal("99.80"),
'dut':Decimal("76.30"),
'eind':Decimal("81.50"),
'ens':Decimal("98.70"),
'epfl':Decimal("94.80"),
'epfr':Decimal("78.10"),
'ethz':Decimal("97.10"),
'frei':Decimal("89.50"),
'git':Decimal("91.30"),
'glas':Decimal("91.20"),
'hels':Decimal("80.40"),
'hkpu':Decimal("91.40"),
'hkst':Decimal("96.20"),
'hku':Decimal("77.00"),
'humb':Decimal("94.70"),
'icl':Decimal("95.10"),
'indis':Decimal("49.30"),
'itmo':Decimal("98.70"),
'kcl':Decimal("86.30"),
'kist':Decimal("64.20"),
'kit':Decimal("84.40"),
'kth':Decimal("83.60"),
'kuj':Decimal("49.50"),
'kul':Decimal("92.00"),
'lms':Decimal("61.00"),
'man':Decimal("62.90"),
'mcp':Decimal("94.60"),
'mel':Decimal("83.70"),
'mil':Decimal("69.20"),
'mit':Decimal("99.40"),
'naji':Decimal("48.80"),
'ntu':Decimal("90.40"),
'ntw':Decimal("66.60"),
'nyu':Decimal("99.40"),
'oxf':Decimal("98.80"),
'pud':Decimal("70.80"),
'qut':Decimal("82.80"),
'rcu':Decimal("99.40"),
'rwth':Decimal("70.80"),
'shJi':Decimal("62.40"),
'sing':Decimal("83.00"),
'sou':Decimal("75.50"),
'stut':Decimal("61.10"),
'tech':Decimal("85.10"),
'tlavu':Decimal("89.00"),
'tsu':Decimal("76.70"),
'tub':Decimal("71.00"),
'tud':Decimal("75.90"),
'tum':Decimal("87.90"),
'ucl':Decimal("87.60"),
'ued':Decimal("89.70"),
'uiu':Decimal("99.20"),
'unlu':Decimal("87.40"),
'unsw':Decimal("70.50"),
'unt':Decimal("99.60"),
'uta':Decimal("99.60"),
'utj':Decimal("48.70"),
'utw':Decimal("87.00"),
'uwa':Decimal("91.30"),
'wash':Decimal("99.30"),
'wtu':Decimal("73.70"),
'zhej':Decimal("60.70"),
},
'gind': {
'albt':Decimal("75.40"),
'anu':Decimal("48.10"),
'ariz':Decimal("42.00"),
'bju':Decimal("99.40"),
'bro':Decimal("38.60"),
'calt':Decimal("85.90"),
'cbu':Decimal("45.70"),
'chku':Decimal("49.90"),
'cihk':Decimal("67.90"),
'cir':Decimal("40.40"),
'cmel':Decimal("71.10"),
'cou':Decimal("45.70"),
'csb':Decimal("74.90"),
'csd':Decimal("59.80"),
'dut':Decimal("90.10"),
'eind':Decimal("45.80"),
'ens':Decimal("43.50"),
'epfl':Decimal("42.70"),
'epfr':Decimal("62.90"),
'ethz':Decimal("64.10"),
'frei':Decimal("99.90"),
'git':Decimal("79.50"),
'glas':Decimal("39.20"),
'hels':Decimal("39.50"),
'hkpu':Decimal("41.50"),
'hkst':Decimal("55.80"),
'hku':Decimal("39.50"),
'humb':Decimal("45.50"),
'icl':Decimal("49.90"),
'indis':Decimal("41.50"),
'itmo':Decimal("68.70"),
'kcl':Decimal("38.30"),
'kist':Decimal("92.80"),
'kit':Decimal("76.80"),
'kth':Decimal("39.20"),
'kuj':Decimal("51.40"),
'kul':Decimal("88.30"),
'lms':Decimal("87.80"),
'man':Decimal("42.10"),
'mcp':Decimal("51.70"),
'mel':Decimal("50.40"),
'mil':Decimal("38.50"),
'mit':Decimal("87.50"),
'naji':Decimal("74.40"),
'ntu':Decimal("86.90"),
'ntw':Decimal("67.60"),
'nyu':Decimal("39.80"),
'oxf':Decimal("44.30"),
'pud':Decimal("56.70"),
'qut':Decimal("63.00"),
'rcu':Decimal("46.10"),
'rwth':Decimal("89.40"),
'shJi':Decimal("38.50"),
'sing':Decimal("50.60"),
'sou':Decimal("43.20"),
'stut':Decimal("97.80"),
'tech':Decimal("40.10"),
'tlavu':Decimal("38.60"),
'tsu':Decimal("85.90"),
'tub':Decimal("99.90"),
'tud':Decimal("66.50"),
'tum':Decimal("95.10"),
'ucl':Decimal("42.40"),
'ued':Decimal("38.80"),
'uiu':Decimal("42.20"),
'unlu':Decimal("54.10"),
'unsw':Decimal("44.30"),
'unt':Decimal("38.40"),
'uta':Decimal("49.70"),
'utj':Decimal("49.60"),
'utw':Decimal("60.00"),
'uwa':Decimal("41.50"),
'wash':Decimal("41.20"),
'wtu':Decimal("62.20"),
'zhej':Decimal("75.70"),
},
'gint': {
'albt':Decimal("91.90"),
'anu':Decimal("90.00"),
'ariz':Decimal("59.30"),
'bju':Decimal("30.70"),
'bro':Decimal("52.30"),
'calt':Decimal("59.10"),
'cbu':Decimal("66.90"),
'chku':Decimal("75.60"),
'cihk':Decimal("76.20"),
'cir':Decimal("65.10"),
'cmel':Decimal("58.90"),
'cou':Decimal("55.70"),
'csb':Decimal("72.90"),
'csd':Decimal("39.70"),
'dut':Decimal("69.80"),
'eind':Decimal("72.20"),
'ens':Decimal("69.60"),
'epfl':Decimal("97.20"),
'epfr':Decimal("85.30"),
'ethz':Decimal("93.60"),
'frei':Decimal("49.70"),
'git':Decimal("63.00"),
'glas':Decimal("85.80"),
'hels':Decimal("50.60"),
'hkpu':Decimal("73.20"),
'hkst':Decimal("84.40"),
'hku':Decimal("96.80"),
'humb':Decimal("41.50"),
'icl':Decimal("94.30"),
'indis':Decimal("20.10"),
'itmo':Decimal("39.20"),
'kcl':Decimal("95.10"),
'kist':Decimal("31.60"),
'kit':Decimal("41.30"),
'kth':Decimal("71.60"),
'kuj':Decimal("28.30"),
'kul':Decimal("46.00"),
'lms':Decimal("31.10"),
'man':Decimal("84.10"),
'mcp':Decimal("29.80"),
'mel':Decimal("83.30"),
'mil':Decimal("44.10"),
'mit':Decimal("73.90"),
'naji':Decimal("39.70"),
'ntu':Decimal("92.90"),
'ntw':Decimal("25.50"),
'nyu':Decimal("78.00"),
'oxf':Decimal("93.60"),
'pud':Decimal("58.10"),
'qut':Decimal("75.20"),
'rcu':Decimal("63.70"),
'rwth':Decimal("43.70"),
'shJi':Decimal("22.80"),
'sing':Decimal("95.30"),
'sou':Decimal("87.40"),
'stut':Decimal("36.30"),
'tech':Decimal("51.70"),
'tlavu':Decimal("45.30"),
'tsu':Decimal("27.10"),
'tub':Decimal("55.40"),
'tud':Decimal("53.70"),
'tum':Decimal("52.90"),
'ucl':Decimal("94.70"),
'ued':Decimal("95.00"),
'uiu':Decimal("51.40"),
'unlu':Decimal("99.70"),
'unsw':Decimal("87.00"),
'unt':Decimal("77.60"),
'uta':Decimal("31.60"),
'utj':Decimal("25.80"),
'utw':Decimal("69.00"),
'uwa':Decimal("72.90"),
'wash':Decimal("57.40"),
'wtu':Decimal("51.90"),
'zhej':Decimal("22.60"),
},
'gres': {
'albt':Decimal("53.30"),
'anu':Decimal("73.00"),
'ariz':Decimal("61.80"),
'bju':Decimal("85.30"),
'bro':Decimal("54.90"),
'calt':Decimal("96.00"),
'cbu':Decimal("78.50"),
'chku':Decimal("69.30"),
'cihk':Decimal("44.90"),
'cir':Decimal("64.60"),
'cmel':Decimal("92.30"),
'cou':Decimal("94.10"),
'csb':Decimal("70.90"),
'csd':Decimal("81.60"),
'dut':Decimal("78.30"),
'eind':Decimal("48.40"),
'ens':Decimal("40.90"),
'epfl':Decimal("91.60"),
'epfr':Decimal("60.60"),
'ethz':Decimal("97.30"),
'frei':Decimal("51.60"),
'git':Decimal("99.70"),
'glas':Decimal("52.50"),
'hels':Decimal("49.60"),
'hkpu':Decimal("36.50"),
'hkst':Decimal("92.00"),
'hku':Decimal("73.00"),
'humb':Decimal("31.30"),
'icl':Decimal("87.50"),
'indis':Decimal("76.10"),
'itmo':Decimal("32.00"),
'kcl':Decimal("94.60"),
'kist':Decimal("88.20"),
'kit':Decimal("85.50"),
'kth':Decimal("42.00"),
'kuj':Decimal("72.80"),
'kul':Decimal("55.80"),
'lms':Decimal("68.10"),
'man':Decimal("71.90"),
'mcp':Decimal("89.30"),
'mel':Decimal("70.20"),
'mil':Decimal("64.30"),
'mit':Decimal("95.40"),
'naji':Decimal("76.90"),
'ntu':Decimal("87.70"),
'ntw':Decimal("79.80"),
'nyu':Decimal("77.40"),
'oxf':Decimal("92.00"),
'pud':Decimal("84.80"),
'qut':Decimal("42.60"),
'rcu':Decimal("53.80"),
'rwth':Decimal("85.00"),
'shJi':Decimal("68.30"),
'sing':Decimal("91.30"),
'sou':Decimal("60.70"),
'stut':Decimal("60.60"),
'tech':Decimal("71.00"),
'tlavu':Decimal("57.20"),
'tsu':Decimal("90.20"),
'tub':Decimal("82.40"),
'tud':Decimal("53.60"),
'tum':Decimal("95.10"),
'ucl':Decimal("90.30"),
'ued':Decimal("85.30"),
'uiu':Decimal("83.10"),
'unlu':Decimal("44.20"),
'unsw':Decimal("58.20"),
'unt':Decimal("84.40"),
'uta':Decimal("85.30"),
'utj':Decimal("91.70"),
'utw':Decimal("52.80"),
'uwa':Decimal("82.60"),
'wash':Decimal("88.70"),
'wtu':Decimal("73.50"),
'zhej':Decimal("70.40"),
},
'gtch': {
'albt':Decimal("39.20"),
'anu':Decimal("47.20"),
'ariz':Decimal("28.40"),
'bju':Decimal("83.00"),
'bro':Decimal("58.50"),
'calt':Decimal("91.50"),
'cbu':Decimal("81.20"),
'chku':Decimal("64.10"),
'cihk':Decimal("42.40"),
'cir':Decimal("68.80"),
'cmel':Decimal("88.10"),
'cou':Decimal("81.60"),
'csb':Decimal("65.60"),
'csd':Decimal("75.20"),
'dut':Decimal("64.10"),
'eind':Decimal("32.40"),
'ens':Decimal("71.80"),
'epfl':Decimal("86.30"),
'epfr':Decimal("81.70"),
'ethz':Decimal("89.20"),
'frei':Decimal("54.20"),
'git':Decimal("87.20"),
'glas':Decimal("35.20"),
'hels':Decimal("48.80"),
'hkpu':Decimal("46.80"),
'hkst':Decimal("74.30"),
'hku':Decimal("77.00"),
'humb':Decimal("48.40"),
'icl':Decimal("90.10"),
'indis':Decimal("56.90"),
'itmo':Decimal("58.00"),
'kcl':Decimal("45.50"),
'kist':Decimal("79.40"),
'kit':Decimal("73.80"),
'kth':Decimal("44.80"),
'kuj':Decimal("75.40"),
'kul':Decimal("35.20"),
'lms':Decimal("81.50"),
'man':Decimal("63.50"),
'mcp':Decimal("79.70"),
'mel':Decimal("56.10"),
'mil':Decimal("46.40"),
'mit':Decimal("87.30"),
'naji':Decimal("51.40"),
'ntu':Decimal("76.60"),
'ntw':Decimal("81.50"),
'nyu':Decimal("71.10"),
'oxf':Decimal("94.00"),
'pud':Decimal("76.90"),
'qut':Decimal("45.50"),
'rcu':Decimal("64.10"),
'rwth':Decimal("77.80"),
'shJi':Decimal("66.90"),
'sing':Decimal("89.90"),
'sou':Decimal("48.20"),
'stut':Decimal("54.20"),
'tech':Decimal("54.90"),
'tlavu':Decimal("34.10"),
'tsu':Decimal("88.10"),
'tub':Decimal("66.20"),
'tud':Decimal("46.60"),
'tum':Decimal("87.60"),
'ucl':Decimal("85.50"),
'ued':Decimal("85.70"),
'uiu':Decimal("85.00"),
'unlu':Decimal("35.20"),
'unsw':Decimal("60.20"),
'unt':Decimal("79.90"),
'uta':Decimal("72.60"),
'utj':Decimal("92.00"),
'utw':Decimal("38.20"),
'uwa':Decimal("75.30"),
'wash':Decimal("84.40"),
'wtu':Decimal("61.80"),
'zhej':Decimal("73.50"),
},
}
