# Saved performance Tableau: 
from decimal import Decimal
from collections import OrderedDict
actions = OrderedDict([
('CE-HK-K', {
'name': 'Forign Correspondent HK-K',
'comment': 'Handels-Kammer Köln',
}),
('ID-FH-K', {
'name': 'Graduate Interpreter FH K',
'comment': 'FH Köln',
}),
('ID-UHB', {
'name': 'Graduate Interpreter Uni HD',
'comment': 'Uni Heidelberg',
}),
('ID-USB', {
'name': 'Graduate Interpreter Uni SB',
'comment': 'Uni Saarbrücken',
}),
('SS-HK-K', {
'name': 'Specialized Secretary IHK K',
'comment': 'Handels-Kammer Köln',
}),
('TD-FH-K', {
'name': 'Graduate Translator FH K',
'comment': 'FH Köln',
}),
('TD-FH-M', {
'name': 'Graduate Translator FH M',
'comment': 'FH Muenchen',
}),
('TD-UD', {
'name': 'Graduate Translator Uni D',
'comment': 'Uni Düsseldorf',
}),
('TD-UHB', {
'name': 'Graduate Translator Uni HD',
'comment': 'Uni Heidelberg',
}),
('TD-USB', {
'name': 'Graduate Translator Uni SB',
'comment': 'Uni Saarbrücken',
}),
])
objectives = OrderedDict([
])
criteria = OrderedDict([
('DH', {
'name': 'Distance from Home',
'comment': 'Entfernung des Studien-Orts ',
'version': 'performance',
'preferenceDirection': 'min',
'scale': (Decimal('0.00'), Decimal('1000.00')),
'weight': Decimal('100.00'),
'thresholds': {'ind': (Decimal('25.00'), Decimal('0.00')), 'pref': (Decimal('100.00'), Decimal('0.00'))},
}),
('SP', {
'name': 'Content of the Study Program',
'comment': 'Studiengang',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('10.00')),
'weight': Decimal('80.00'),
'thresholds': {'ind': (Decimal('1.00'), Decimal('0.00')), 'pref': (Decimal('2.00'), Decimal('0.00')), 'veto': (Decimal('7.00'), Decimal('0.00'))},
}),
('BC', {
'name': 'Big City',
'comment': 'No comment',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('2000.00')),
'weight': Decimal('20.00'),
'thresholds': {'ind': (Decimal('0.00'), Decimal('0.10')), 'pref': (Decimal('0.00'), Decimal('0.20'))},
}),
('PP', {
'name': 'Professional Perspectives',
'comment': 'Karriere ',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('10.00')),
'weight': Decimal('30.00'),
'thresholds': {'ind': (Decimal('1.00'), Decimal('0.00')), 'pref': (Decimal('2.00'), Decimal('0.00'))},
}),
('OP', {
'name': 'Prestige',
'comment': 'Prestige',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('0.00'), Decimal('100.00')),
'weight': Decimal('60.00'),
'thresholds': {'ind': (Decimal('5.00'), Decimal('0.00')), 'pref': (Decimal('10.00'), Decimal('0.00'))},
}),
('NI', {
'name': 'Net Professional Incomes',
'comment': 'Netto Einkommens-Erwartung',
'version': 'performance',
'preferenceDirection': 'max',
'scale': (Decimal('100.00'), Decimal('200.00')),
'weight': Decimal('70.00'),
'thresholds': {'ind': (Decimal('5.00'), Decimal('0.00')), 'pref': (Decimal('10.00'), Decimal('0.00'))},
}),
])
evaluation = {
'DH': {
'CE-HK-K':Decimal("-0.00"),
'ID-FH-K':Decimal("-0.00"),
'ID-UHB':Decimal("-275.00"),
'ID-USB':Decimal("-269.00"),
'SS-HK-K':Decimal("-0.00"),
'TD-FH-K':Decimal("-0.00"),
'TD-FH-M':Decimal("-631.00"),
'TD-UD':Decimal("-41.00"),
'TD-UHB':Decimal("-275.00"),
'TD-USB':Decimal("-269.00"),
},
'SP': {
'CE-HK-K':Decimal("2.00"),
'ID-FH-K':Decimal("8.00"),
'ID-UHB':Decimal("8.00"),
'ID-USB':Decimal("8.00"),
'SS-HK-K':Decimal("1.00"),
'TD-FH-K':Decimal("5.00"),
'TD-FH-M':Decimal("4.00"),
'TD-UD':Decimal("5.00"),
'TD-UHB':Decimal("5.00"),
'TD-USB':Decimal("5.00"),
},
'BC': {
'CE-HK-K':Decimal("1015.00"),
'ID-FH-K':Decimal("1015.00"),
'ID-UHB':Decimal("140.00"),
'ID-USB':Decimal("196.00"),
'SS-HK-K':Decimal("1015.00"),
'TD-FH-K':Decimal("1015.00"),
'TD-FH-M':Decimal("1241.00"),
'TD-UD':Decimal("567.00"),
'TD-UHB':Decimal("140.00"),
'TD-USB':Decimal("196.00"),
},
'PP': {
'CE-HK-K':Decimal("4.00"),
'ID-FH-K':Decimal("9.00"),
'ID-UHB':Decimal("9.00"),
'ID-USB':Decimal("9.00"),
'SS-HK-K':Decimal("4.00"),
'TD-FH-K':Decimal("7.00"),
'TD-FH-M':Decimal("7.00"),
'TD-UD':Decimal("7.00"),
'TD-UHB':Decimal("7.00"),
'TD-USB':Decimal("7.00"),
},
'OP': {
'CE-HK-K':Decimal("44.00"),
'ID-FH-K':Decimal("62.00"),
'ID-UHB':Decimal("62.00"),
'ID-USB':Decimal("62.00"),
'SS-HK-K':Decimal("44.00"),
'TD-FH-K':Decimal("62.00"),
'TD-FH-M':Decimal("62.00"),
'TD-UD':Decimal("62.00"),
'TD-UHB':Decimal("62.00"),
'TD-USB':Decimal("62.00"),
},
'NI': {
'CE-HK-K':Decimal("190.85"),
'ID-FH-K':Decimal("166.97"),
'ID-UHB':Decimal("145.74"),
'ID-USB':Decimal("145.74"),
'SS-HK-K':Decimal("190.85"),
'TD-FH-K':Decimal("166.97"),
'TD-FH-M':Decimal("102.87"),
'TD-UD':Decimal("145.74"),
'TD-UHB':Decimal("145.74"),
'TD-USB':Decimal("145.74"),
},
}
