# Saved performance Tableau: 
from decimal import Decimal
from collections import OrderedDict
actions = OrderedDict([
('mv_AL', {
'name': 'Apres lui',
'comment': 'Movie to be seen in town',
}),
('mv_BI', {
'name': 'Because I said so',
'comment': 'Movie to be seen in town',
}),
('mv_CM', {
'name': 'Caramel',
'comment': 'Movie to be seen in town',
}),
('mv_DF', {
'name': 'Death at a Funeral',
'comment': 'Movie to be seen in town',
}),
('mv_DG', {
'name': 'The Dead Girl',
'comment': 'Movie to be seen in town',
}),
('mv_DI', {
'name': 'Disturbia',
'comment': 'Movie to be seen in town',
}),
('mv_DJ', {
'name': 'Dialogue avec mon jardinier',
'comment': 'Movie to be seen in town',
}),
('mv_FC', {
'name': 'La fille coupee en deux',
'comment': 'Movie to be seen in town',
}),
('mv_FF', {
'name': 'Fast Food Nation',
'comment': 'Movie to be seen in town',
}),
('mv_GG', {
'name': "Goya's Ghosts",
'comment': 'Movie to be seen in town',
}),
('mv_GH', {
'name': 'Grindhouse: Planet Terror',
'comment': 'Movie to be seen in town',
}),
('mv_HN', {
'name': 'Half Nelson',
'comment': 'Movie to be seen in town',
}),
('mv_HP', {
'name': 'Harry Potter 5',
'comment': 'Movie to be seen in town',
}),
('mv_HS', {
'name': 'Hairspray',
'comment': 'Movie to be seen in town',
}),
('mv_JB', {
'name': 'Jindabyne',
'comment': 'Movie to be seen in town',
}),
('mv_MB', {
'name': 'Mr Brooks',
'comment': 'Movie to be seen in town',
}),
('mv_NP', {
'name': 'Naissance des pieuvres',
'comment': 'Movie to be seen in town',
}),
('mv_PE', {
'name': "Pleain d'essence",
'comment': 'Movie to be seen in town',
}),
('mv_QS', {
'name': 'Quatre mois, trois semaines',
'comment': 'Movie to be seen in town',
}),
('mv_RG', {
'name': 'Romain de gare',
'comment': 'Movie to be seen in town',
}),
('mv_RR', {
'name': 'Red Road',
'comment': 'Movie to be seen in town',
}),
('mv_SM', {
'name': "The Simpson's Movie",
'comment': 'Movie to be seen in town',
}),
('mv_TF', {
'name': 'Transformers',
'comment': 'Movie to be seen in town',
}),
('mv_TM', {
'name': 'La tete de Maman',
'comment': 'Movie to be seen in town',
}),
('mv_TP', {
'name': 'Two days in Paris',
'comment': 'Movie to be seen in town',
}),
])
objectives = OrderedDict([
])
criteria = OrderedDict([
('AP', {
'name': 'Albert Petesch',
'comment': 'Luxemburger Wort, Telecran',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('AS', {
'name': 'Alain Stevenart',
'comment': 'La Meuse',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('CF', {
'name': 'Claude François',
'comment': 'Luxemburger Wort, Télécran',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('CS', {
'name': 'Christian Spielmann',
'comment': 'Lëtzebuerger Journal',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('DR', {
'name': 'Duncan Roberts',
'comment': '352 Magazine',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('FG', {
'name': 'Frank Grotz',
'comment': 'Lëtzebuerger Land',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('GS', {
'name': 'Gabrielle Seil',
'comment': 'Revue',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('JH', {
'name': 'Joy Hoffmann',
'comment': 'Zinemag',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('3.00'),
'thresholds': {},
}),
('JPT', {
'name': 'Jean-Pierre Thiltges',
'comment': 'Revue, Télé Revue, Hebdo Revue, Graffiti',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('MR', {
'name': 'Martine Reuter',
'comment': 'Tageblatt, Radio 100,7',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('RR', {
'name': 'Raoul Reis',
'comment': 'Radio ARA, Radio Amizade, www.bondis.lu',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('SF', {
'name': 'Sylvie Flammang',
'comment': 'Radio 100,7',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('SJ', {
'name': 'Susanne Jaspers',
'comment': 'Radio 100,7',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('TD', {
'name': 'Thibaut Demeyer',
'comment': 'Woxx, La Voix du Luxembourg',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('1.00'),
'thresholds': {},
}),
('VT', {
'name': 'Vivianne Thill',
'comment': 'Movie critic, Le jeudi',
'preferenceDirection': 'max',
'scale': (Decimal('-2.00'), Decimal('5.00')),
'weight': Decimal('3.00'),
'thresholds': {},
}),
])
evaluation = {
'AP': {
'mv_AL':Decimal("3.00"),
'mv_BI':Decimal("1.00"),
'mv_CM':Decimal("-999.00"),
'mv_DF':Decimal("-999.00"),
'mv_DG':Decimal("3.00"),
'mv_DI':Decimal("1.00"),
'mv_DJ':Decimal("3.00"),
'mv_FC':Decimal("3.00"),
'mv_FF':Decimal("2.00"),
'mv_GG':Decimal("2.00"),
'mv_GH':Decimal("1.00"),
'mv_HN':Decimal("3.00"),
'mv_HP':Decimal("1.00"),
'mv_HS':Decimal("2.00"),
'mv_JB':Decimal("3.00"),
'mv_MB':Decimal("-999.00"),
'mv_NP':Decimal("-999.00"),
'mv_PE':Decimal("3.00"),
'mv_QS':Decimal("-999.00"),
'mv_RG':Decimal("2.00"),
'mv_RR':Decimal("3.00"),
'mv_SM':Decimal("3.00"),
'mv_TF':Decimal("-1.00"),
'mv_TM':Decimal("2.00"),
'mv_TP':Decimal("2.00"),
},
'AS': {
'mv_AL':Decimal("-1.00"),
'mv_BI':Decimal("-1.00"),
'mv_CM':Decimal("3.00"),
'mv_DF':Decimal("4.00"),
'mv_DG':Decimal("2.00"),
'mv_DI':Decimal("2.00"),
'mv_DJ':Decimal("1.00"),
'mv_FC':Decimal("2.00"),
'mv_FF':Decimal("3.00"),
'mv_GG':Decimal("3.00"),
'mv_GH':Decimal("-999.00"),
'mv_HN':Decimal("1.00"),
'mv_HP':Decimal("-999.00"),
'mv_HS':Decimal("4.00"),
'mv_JB':Decimal("4.00"),
'mv_MB':Decimal("2.00"),
'mv_NP':Decimal("1.00"),
'mv_PE':Decimal("4.00"),
'mv_QS':Decimal("3.00"),
'mv_RG':Decimal("2.00"),
'mv_RR':Decimal("2.00"),
'mv_SM':Decimal("3.00"),
'mv_TF':Decimal("-999.00"),
'mv_TM':Decimal("1.00"),
'mv_TP':Decimal("3.00"),
},
'CF': {
'mv_AL':Decimal("2.00"),
'mv_BI':Decimal("1.00"),
'mv_CM':Decimal("3.00"),
'mv_DF':Decimal("3.00"),
'mv_DG':Decimal("2.00"),
'mv_DI':Decimal("-999.00"),
'mv_DJ':Decimal("3.00"),
'mv_FC':Decimal("2.00"),
'mv_FF':Decimal("2.00"),
'mv_GG':Decimal("3.00"),
'mv_GH':Decimal("1.00"),
'mv_HN':Decimal("3.00"),
'mv_HP':Decimal("3.00"),
'mv_HS':Decimal("2.00"),
'mv_JB':Decimal("3.00"),
'mv_MB':Decimal("-999.00"),
'mv_NP':Decimal("3.00"),
'mv_PE':Decimal("2.00"),
'mv_QS':Decimal("2.00"),
'mv_RG':Decimal("2.00"),
'mv_RR':Decimal("-999.00"),
'mv_SM':Decimal("2.00"),
'mv_TF':Decimal("1.00"),
'mv_TM':Decimal("2.00"),
'mv_TP':Decimal("3.00"),
},
'CS': {
'mv_AL':Decimal("-1.00"),
'mv_BI':Decimal("1.00"),
'mv_CM':Decimal("2.00"),
'mv_DF':Decimal("1.00"),
'mv_DG':Decimal("3.00"),
'mv_DI':Decimal("1.00"),
'mv_DJ':Decimal("-999.00"),
'mv_FC':Decimal("1.00"),
'mv_FF':Decimal("1.00"),
'mv_GG':Decimal("1.00"),
'mv_GH':Decimal("-1.00"),
'mv_HN':Decimal("1.00"),
'mv_HP':Decimal("1.00"),
'mv_HS':Decimal("3.00"),
'mv_JB':Decimal("-999.00"),
'mv_MB':Decimal("-999.00"),
'mv_NP':Decimal("1.00"),
'mv_PE':Decimal("-999.00"),
'mv_QS':Decimal("-999.00"),
'mv_RG':Decimal("2.00"),
'mv_RR':Decimal("1.00"),
'mv_SM':Decimal("2.00"),
'mv_TF':Decimal("1.00"),
'mv_TM':Decimal("2.00"),
'mv_TP':Decimal("1.00"),
},
'DR': {
'mv_AL':Decimal("-999.00"),
'mv_BI':Decimal("-1.00"),
'mv_CM':Decimal("-999.00"),
'mv_DF':Decimal("2.00"),
'mv_DG':Decimal("3.00"),
'mv_DI':Decimal("2.00"),
'mv_DJ':Decimal("-999.00"),
'mv_FC':Decimal("3.00"),
'mv_FF':Decimal("2.00"),
'mv_GG':Decimal("-999.00"),
'mv_GH':Decimal("2.00"),
'mv_HN':Decimal("3.00"),
'mv_HP':Decimal("-999.00"),
'mv_HS':Decimal("2.00"),
'mv_JB':Decimal("3.00"),
'mv_MB':Decimal("1.00"),
'mv_NP':Decimal("-999.00"),
'mv_PE':Decimal("3.00"),
'mv_QS':Decimal("4.00"),
'mv_RG':Decimal("-999.00"),
'mv_RR':Decimal("4.00"),
'mv_SM':Decimal("2.00"),
'mv_TF':Decimal("1.00"),
'mv_TM':Decimal("-999.00"),
'mv_TP':Decimal("2.00"),
},
'FG': {
'mv_AL':Decimal("-999.00"),
'mv_BI':Decimal("-999.00"),
'mv_CM':Decimal("-999.00"),
'mv_DF':Decimal("-999.00"),
'mv_DG':Decimal("1.00"),
'mv_DI':Decimal("2.00"),
'mv_DJ':Decimal("-999.00"),
'mv_FC':Decimal("-999.00"),
'mv_FF':Decimal("2.00"),
'mv_GG':Decimal("-999.00"),
'mv_GH':Decimal("2.00"),
'mv_HN':Decimal("-999.00"),
'mv_HP':Decimal("-999.00"),
'mv_HS':Decimal("2.00"),
'mv_JB':Decimal("2.00"),
'mv_MB':Decimal("-999.00"),
'mv_NP':Decimal("3.00"),
'mv_PE':Decimal("1.00"),
'mv_QS':Decimal("3.00"),
'mv_RG':Decimal("-999.00"),
'mv_RR':Decimal("-999.00"),
'mv_SM':Decimal("2.00"),
'mv_TF':Decimal("-999.00"),
'mv_TM':Decimal("-999.00"),
'mv_TP':Decimal("-999.00"),
},
'GS': {
'mv_AL':Decimal("3.00"),
'mv_BI':Decimal("-999.00"),
'mv_CM':Decimal("3.00"),
'mv_DF':Decimal("1.00"),
'mv_DG':Decimal("4.00"),
'mv_DI':Decimal("-999.00"),
'mv_DJ':Decimal("3.00"),
'mv_FC':Decimal("1.00"),
'mv_FF':Decimal("-999.00"),
'mv_GG':Decimal("1.00"),
'mv_GH':Decimal("1.00"),
'mv_HN':Decimal("4.00"),
'mv_HP':Decimal("-999.00"),
'mv_HS':Decimal("2.00"),
'mv_JB':Decimal("3.00"),
'mv_MB':Decimal("1.00"),
'mv_NP':Decimal("2.00"),
'mv_PE':Decimal("-999.00"),
'mv_QS':Decimal("-999.00"),
'mv_RG':Decimal("3.00"),
'mv_RR':Decimal("4.00"),
'mv_SM':Decimal("-999.00"),
'mv_TF':Decimal("-999.00"),
'mv_TM':Decimal("2.00"),
'mv_TP':Decimal("-999.00"),
},
'JH': {
'mv_AL':Decimal("-999.00"),
'mv_BI':Decimal("-999.00"),
'mv_CM':Decimal("2.00"),
'mv_DF':Decimal("3.00"),
'mv_DG':Decimal("3.00"),
'mv_DI':Decimal("1.00"),
'mv_DJ':Decimal("-999.00"),
'mv_FC':Decimal("3.00"),
'mv_FF':Decimal("1.00"),
'mv_GG':Decimal("-1.00"),
'mv_GH':Decimal("2.00"),
'mv_HN':Decimal("3.00"),
'mv_HP':Decimal("1.00"),
'mv_HS':Decimal("3.00"),
'mv_JB':Decimal("2.00"),
'mv_MB':Decimal("2.00"),
'mv_NP':Decimal("3.00"),
'mv_PE':Decimal("2.00"),
'mv_QS':Decimal("4.00"),
'mv_RG':Decimal("1.00"),
'mv_RR':Decimal("3.00"),
'mv_SM':Decimal("3.00"),
'mv_TF':Decimal("1.00"),
'mv_TM':Decimal("2.00"),
'mv_TP':Decimal("3.00"),
},
'JPT': {
'mv_AL':Decimal("2.00"),
'mv_BI':Decimal("2.00"),
'mv_CM':Decimal("3.00"),
'mv_DF':Decimal("2.00"),
'mv_DG':Decimal("3.00"),
'mv_DI':Decimal("2.00"),
'mv_DJ':Decimal("2.00"),
'mv_FC':Decimal("3.00"),
'mv_FF':Decimal("2.00"),
'mv_GG':Decimal("-999.00"),
'mv_GH':Decimal("1.00"),
'mv_HN':Decimal("2.00"),
'mv_HP':Decimal("1.00"),
'mv_HS':Decimal("4.00"),
'mv_JB':Decimal("3.00"),
'mv_MB':Decimal("2.00"),
'mv_NP':Decimal("3.00"),
'mv_PE':Decimal("4.00"),
'mv_QS':Decimal("4.00"),
'mv_RG':Decimal("2.00"),
'mv_RR':Decimal("3.00"),
'mv_SM':Decimal("2.00"),
'mv_TF':Decimal("2.00"),
'mv_TM':Decimal("2.00"),
'mv_TP':Decimal("2.00"),
},
'MR': {
'mv_AL':Decimal("-999.00"),
'mv_BI':Decimal("-999.00"),
'mv_CM':Decimal("2.00"),
'mv_DF':Decimal("2.00"),
'mv_DG':Decimal("3.00"),
'mv_DI':Decimal("2.00"),
'mv_DJ':Decimal("2.00"),
'mv_FC':Decimal("3.00"),
'mv_FF':Decimal("2.00"),
'mv_GG':Decimal("-1.00"),
'mv_GH':Decimal("3.00"),
'mv_HN':Decimal("-999.00"),
'mv_HP':Decimal("2.00"),
'mv_HS':Decimal("2.00"),
'mv_JB':Decimal("2.00"),
'mv_MB':Decimal("1.00"),
'mv_NP':Decimal("3.00"),
'mv_PE':Decimal("2.00"),
'mv_QS':Decimal("3.00"),
'mv_RG':Decimal("2.00"),
'mv_RR':Decimal("4.00"),
'mv_SM':Decimal("2.00"),
'mv_TF':Decimal("-999.00"),
'mv_TM':Decimal("3.00"),
'mv_TP':Decimal("-999.00"),
},
'RR': {
'mv_AL':Decimal("-999.00"),
'mv_BI':Decimal("2.00"),
'mv_CM':Decimal("1.00"),
'mv_DF':Decimal("2.00"),
'mv_DG':Decimal("-999.00"),
'mv_DI':Decimal("-999.00"),
'mv_DJ':Decimal("-999.00"),
'mv_FC':Decimal("2.00"),
'mv_FF':Decimal("1.00"),
'mv_GG':Decimal("2.00"),
'mv_GH':Decimal("4.00"),
'mv_HN':Decimal("1.00"),
'mv_HP':Decimal("3.00"),
'mv_HS':Decimal("3.00"),
'mv_JB':Decimal("-999.00"),
'mv_MB':Decimal("2.00"),
'mv_NP':Decimal("2.00"),
'mv_PE':Decimal("-999.00"),
'mv_QS':Decimal("3.00"),
'mv_RG':Decimal("1.00"),
'mv_RR':Decimal("3.00"),
'mv_SM':Decimal("3.00"),
'mv_TF':Decimal("-1.00"),
'mv_TM':Decimal("-999.00"),
'mv_TP':Decimal("2.00"),
},
'SF': {
'mv_AL':Decimal("-999.00"),
'mv_BI':Decimal("-999.00"),
'mv_CM':Decimal("2.00"),
'mv_DF':Decimal("3.00"),
'mv_DG':Decimal("-999.00"),
'mv_DI':Decimal("1.00"),
'mv_DJ':Decimal("2.00"),
'mv_FC':Decimal("-999.00"),
'mv_FF':Decimal("2.00"),
'mv_GG':Decimal("-999.00"),
'mv_GH':Decimal("-999.00"),
'mv_HN':Decimal("-999.00"),
'mv_HP':Decimal("-999.00"),
'mv_HS':Decimal("-999.00"),
'mv_JB':Decimal("2.00"),
'mv_MB':Decimal("-999.00"),
'mv_NP':Decimal("3.00"),
'mv_PE':Decimal("3.00"),
'mv_QS':Decimal("4.00"),
'mv_RG':Decimal("-999.00"),
'mv_RR':Decimal("3.00"),
'mv_SM':Decimal("-999.00"),
'mv_TF':Decimal("-999.00"),
'mv_TM':Decimal("2.00"),
'mv_TP':Decimal("-999.00"),
},
'SJ': {
'mv_AL':Decimal("2.00"),
'mv_BI':Decimal("-999.00"),
'mv_CM':Decimal("2.00"),
'mv_DF':Decimal("-1.00"),
'mv_DG':Decimal("-1.00"),
'mv_DI':Decimal("1.00"),
'mv_DJ':Decimal("4.00"),
'mv_FC':Decimal("2.00"),
'mv_FF':Decimal("1.00"),
'mv_GG':Decimal("-1.00"),
'mv_GH':Decimal("-999.00"),
'mv_HN':Decimal("3.00"),
'mv_HP':Decimal("1.00"),
'mv_HS':Decimal("1.00"),
'mv_JB':Decimal("2.00"),
'mv_MB':Decimal("2.00"),
'mv_NP':Decimal("-999.00"),
'mv_PE':Decimal("3.00"),
'mv_QS':Decimal("-999.00"),
'mv_RG':Decimal("-999.00"),
'mv_RR':Decimal("-999.00"),
'mv_SM':Decimal("2.00"),
'mv_TF':Decimal("-1.00"),
'mv_TM':Decimal("-999.00"),
'mv_TP':Decimal("1.00"),
},
'TD': {
'mv_AL':Decimal("-999.00"),
'mv_BI':Decimal("-999.00"),
'mv_CM':Decimal("-999.00"),
'mv_DF':Decimal("-999.00"),
'mv_DG':Decimal("-999.00"),
'mv_DI':Decimal("-999.00"),
'mv_DJ':Decimal("3.00"),
'mv_FC':Decimal("1.00"),
'mv_FF':Decimal("3.00"),
'mv_GG':Decimal("-999.00"),
'mv_GH':Decimal("-999.00"),
'mv_HN':Decimal("3.00"),
'mv_HP':Decimal("2.00"),
'mv_HS':Decimal("3.00"),
'mv_JB':Decimal("-999.00"),
'mv_MB':Decimal("2.00"),
'mv_NP':Decimal("-999.00"),
'mv_PE':Decimal("-999.00"),
'mv_QS':Decimal("4.00"),
'mv_RG':Decimal("3.00"),
'mv_RR':Decimal("4.00"),
'mv_SM':Decimal("2.00"),
'mv_TF':Decimal("1.00"),
'mv_TM':Decimal("4.00"),
'mv_TP':Decimal("-999.00"),
},
'VT': {
'mv_AL':Decimal("2.00"),
'mv_BI':Decimal("-999.00"),
'mv_CM':Decimal("2.00"),
'mv_DF':Decimal("1.00"),
'mv_DG':Decimal("3.00"),
'mv_DI':Decimal("-999.00"),
'mv_DJ':Decimal("-1.00"),
'mv_FC':Decimal("3.00"),
'mv_FF':Decimal("1.00"),
'mv_GG':Decimal("1.00"),
'mv_GH':Decimal("-999.00"),
'mv_HN':Decimal("3.00"),
'mv_HP':Decimal("-999.00"),
'mv_HS':Decimal("-999.00"),
'mv_JB':Decimal("3.00"),
'mv_MB':Decimal("-999.00"),
'mv_NP':Decimal("3.00"),
'mv_PE':Decimal("3.00"),
'mv_QS':Decimal("4.00"),
'mv_RG':Decimal("-999.00"),
'mv_RR':Decimal("2.00"),
'mv_SM':Decimal("3.00"),
'mv_TF':Decimal("-999.00"),
'mv_TM':Decimal("-999.00"),
'mv_TP':Decimal("2.00"),
},
}
