# example of sorting profile
categories = {
    'c01': { 'name': 'week',
            'order': 0,
            'comment': 'lowest category',
        },
    'c02': { 'name': 'ok',
            'order': 1,
            'comment': 'medium category',
        },
    'c03': { 'name': 'good',
            'order': 2,
            'comment': 'highest category',
        },
    'c04': { 'name': 'excellent',
            'order': 3,
            'comment': 'highest category',
        },
    }

criteriaCategoryLimits = {
    'g01': { 'c01': {'minimum':0, 'maximum':25},
             'c02': {'minimum':25, 'maximum':50},
             'c03': {'minimum':50, 'maximum':75},
             'c04': {'minimum':75, 'maximum':100},
        },
    'g02': { 'c01': {'minimum':0, 'maximum':25},
             'c02': {'minimum':25, 'maximum':50},
             'c03': {'minimum':50, 'maximum':75},
             'c04': {'minimum':75, 'maximum':100},
        },
    'g03': { 'c01': {'minimum':0, 'maximum':25},
             'c02': {'minimum':25, 'maximum':50},
             'c03': {'minimum':50, 'maximum':75},
             'c04': {'minimum':75, 'maximum':100},
        },
    'g04': { 'c01': {'minimum':0, 'maximum':25},
             'c02': {'minimum':25, 'maximum':50},
             'c03': {'minimum':50, 'maximum':75},
             'c04': {'minimum':75, 'maximum':100},
        },
    'g05': { 'c01': {'minimum':0, 'maximum':25},
             'c02': {'minimum':25, 'maximum':50},
             'c03': {'minimum':50, 'maximum':75},
             'c04': {'minimum':75, 'maximum':100},
        },
    }
